### PR TITLE
Extract CLI module

### PR DESCRIPTION
**Pull request by chulkilee**
To separate CLI and library - see #2

### CODE REVIEW

**Comment by copiousfreetime** [comment]
@chulkilee Since highline is your reasoning here. Quick question. Are you on Ruby 2.0 or 2.2? I'm thinking that what I might do is just bump the minimum requirement to Ruby 2.0 and use the standard library `io/console` since the console needs of htauth are very small. that way we  can just remove highline as a dependency all together.

**Comment by chulkilee** [comment]
I'm using Ruby 2.2

**Comment by copiousfreetime** [comment]
@chulkilee sounds good. I've done #9 as a replacement. I'm going to release a 2.0 version with that and a bunch of tomdoc documentation on things in it. So that'll be in a week or so.

**Comment by copiousfreetime** [comment]
Closing as I've done this in d27e157

**Pull request closed without merging**
