### PR TITLE
do not calculate digest when reading existing line

### PR DESCRIPTION
**Pull request by chulkilee**
It allows much much faster loading time for a huge htpasswd file.

### CODE REVIEW

**Comment by copiousfreetime** [comment]
Can you add a test that shows why this is needed?

**Comment by copiousfreetime** [comment]
My apologies this doesn't need a test, I misread.

**Comment by copiousfreetime** [comment]
@chulkilee I think fd42d53 is a better way to resolve this. Creates a more appropriate default case. Thoughts?

**Comment by chulkilee** [comment]
@copiousfreetime I wanted to leave the default behavior - empty password, not nil password by default. If you think it's okay to use nil, then fd42d53 looks good to me

**Comment by chulkilee** [comment]
closing it since the commit is in already master. Thanks!

**Comment by chulkilee** [comment]
Could you release a new version? I'd like to use released version, not github commit from my production service :)

**Comment by copiousfreetime** [comment]
@chulkilee absolutely, I'm going to go over the cli extraction you did last year first and probably merge it and do a release. 

If I may ask, what all are you using htauth for ?

**Comment by chulkilee** [comment]
Basically read a large htpasswd file (300KB) and validate credentials from user input. I have own method to parse and handle htgroup files, but htpasswd has more thing to consider, such as different algorithm, which is done nicely by this gem.

**Comment by copiousfreetime** [comment]
Version 1.2.0 pushed with your performance update.

**Pull request closed without merging**
